name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            cd ${{ secrets.DEPLOY_PATH }}

            # Ensure git directory is safe
            git config --global --add safe.directory ${{ secrets.DEPLOY_PATH }}

            # Pull latest changes
            git reset --hard
            git pull origin main

            # Install dependencies and build
            npm ci
            npm run build

            # Use full path for PM2
            ~/.nvm/versions/node/$(node -v)/bin/pm2 reload ai-image-generator --update-env || \
            ~/.nvm/versions/node/$(node -v)/bin/pm2 start npm --name 'ai-image-generator' -- start --cwd ${{ secrets.DEPLOY_PATH }}
          "
