name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup SSH key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # 3️⃣ Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            # Load NVM
            export NVM_DIR=\"$HOME/.nvm\"
            [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"

            # Go to deploy path
            cd ${{ secrets.DEPLOY_PATH }}

            # Fix Git ownership issue
            git config --global --add safe.directory ${{ secrets.DEPLOY_PATH }}

            # Pull latest changes
            git reset --hard
            git pull origin main

            # Install dependencies and build
            npm ci
            npm run build

            # Restart app with PM2
            pm2 delete ai-image-generator || true
            pm2 start npm --name 'ai-image-generator' -- start
          "
